### PR TITLE
adding ubuntu build instructions

### PR DESCRIPTION
**Pull request by Entkenntnis**
I have put this guide together for all the people out there who wants to run the game!

### CODE REVIEW

**Comment by Andrettin** [comment]
Thank you! :)

**Comment by Entkenntnis** [comment]
I am wondering: What are the optional requirements for? Are they somewhere important?
e.g. Sqlite, Mikmod, Theora, FluidSynth, Mng, PhysFS, Stacktrace

**Comment by Andrettin** [comment]
The optional requirements are largely for engine features that are present in Stratagus, but aren't used by Wyrmsun. FluidSynth, for instance, is used for .midi files, which Wyrmsun doesn't use.

**Comment by Entkenntnis** [comment]
thanks, happy to see wyrmsun alive!

**Pull request merged**
