### PR TITLE
Crashfix

### PR DESCRIPTION
**Pull request by marcelofg55**
- Prevent MenuScreen for stopping twice, this prevents a crash in case menu:stop is called twice.

I got this crash when a game finished and you hit "Continue" too fast.

### CODE REVIEW

**Comment by akien-mga** [comment]
This will have to be rebased, or closed and cherry-picked in a new branch, as there is a lot of mess now, probably due to an unhappy freeze push.

Note that you can do pull request from branches, so that you can have several pull requests at once.

**Comment by marcelofg55** [comment]
I'm not sure how this got so messy, it was supposed to only be this commit https://github.com/marcelofg55/Wyrmgus/commit/56a3868c255ebaf31cb60d35bc0cfc79ec2675ce

**Comment by Andrettin** [comment]
It seems like GitHub is considering the pull request to revert all of the latest changes. I thought I had already merged this, though...

**Comment by marcelofg55** [comment]
I've just checked and it's not merged, want me to close and re-open the pull request? Or if you want to merge the commit it might be easier :) https://github.com/marcelofg55/Wyrmgus/commit/56a3868c255ebaf31cb60d35bc0cfc79ec2675ce

**Comment by Andrettin** [comment]
I've merged it manually now:
https://github.com/Andrettin/Wyrmgus/commit/4704db936a8b5a806b0607aa0af2e77d68b43c39

Thanks for the fix! :)

**Pull request closed without merging**
