### PR TITLE
Update astar.cpp

### PR DESCRIPTION
**Pull request by BeWorld2018**
MORPHOS Support

### CODE REVIEW

**Comment by BeWorld2018** [comment]
you can delete modification of astar.cpp file, thanks

**Comment by Andrettin** [comment]
Hey, so you mean that this modification isn't necessary for MORPHOS?

**Comment by BeWorld2018** [comment]
yes, dont modify this file, if you can delete this pull request, thank

Happyyyy New Year 2019 !!

**Comment by Andrettin** [comment]
Happy 2019 to you too! :)

**Pull request closed without merging**
